### ISSUE TITLE
Popover has lower z-index than resize-handle

### ISSUE THREAD

**Issue by johanrd** [NullVoxPopuli/limber#1641]
https://limber.glimdown.com/edit?c=Q&forceEditor=true&format=gjs

<img width="938" alt="Screenshot 2024-02-05 at 01 00 40" src="https://github.com/NullVoxPopuli/limber/assets/4601554/c37b219d-faa2-4ee7-ba9b-529d872bb7da">

Two different ways to solve this:
1) https://github.com/johanrd/limber/commit/c751df1f81e7b674a245ee68580159dbe3a6f4c9 – this is perhaps to prefer (if there are no remembered reason for the `z-10`, of course)
2) https://github.com/johanrd/limber/commit/b2e7f776bcf2861cee49bc51106f0062be484677 – this is just to point to the where the other z-index is. Could perhaps be solved by setting `class="z-20"` on the menu component, and spread it with ...attributes.

**Comment by NullVoxPopuli** [comment]
Fixed in https://github.com/NullVoxPopuli/limber/pull/1642
