### ISSUE TITLE
404 from swapi.dev

### ISSUE THREAD

**Issue by johanrd** [NullVoxPopuli/limber#1685]
1. Go here: https://tutorial.glimdown.com/11-requesting-data/1-using-remote-data?showAnswer=1
See 404 from swapi.dev
<img width="1800" alt="Screenshot 2024-03-07 at 21 29 54" src="https://github.com/NullVoxPopuli/limber/assets/4601554/49c0a972-1a8a-4b52-a129-21ccdcb2fffc">

Not sure if just temporary, but others have created a [clone](https://github.com/semperry/swapi?tab=readme-ov-file) at swapi.tech, because `original is not maintained`, which may be a symptom of the general stability of swapi.dev. 

Not sure, posting as an issue anyways.

**Comment by NullVoxPopuli** [comment]
oh no! I guess it's time to find and replace swapi.dev for swapi.tech
