### ISSUE TITLE
Some 404 errors on startup tutorial

### ISSUE THREAD

**Issue by chsanch** [NullVoxPopuli/limber#813]
Hi!
I've just cloned the repo, installed the dependencies, and started it with the command `pnpm run start:tutorial -- --port 4201`, the app seems to start properly:

```
tutorial:start: Building into /private/var/folders/3m/5qk_qwcd7r9dk6txxw00g4gr0000gp/T/embroider/7e15f3
tutorial:start: - building...
tutorial:start:
tutorial:start: Build successful (5250ms) – Serving on http://localhost:4201/
tutorial:start:
tutorial:start: Slowest Nodes (totalTime >= 5%) | Total (avg)
tutorial:start: -+-
tutorial:start: @embroider/webpack (1) | 3277ms
tutorial:start: @embroider/compat/addons (1) | 430ms
tutorial:start: @embroider/compat/app (1) | 388ms
tutorial:start:
```
but opening the url, I'm getting these errors:
<img width="1609" alt="limber-tutorial-errors" src="https://user-images.githubusercontent.com/159034/229278114-6f88c0cf-bf51-4942-ae2a-6759469e27b4.png">

Not sure if I'm missing a configuration here?

**Comment by NullVoxPopuli** [comment]
Yeah! The other app, at apps/repl needs to be started on port 4201

Super apologies for not documenting this 😢

In each directory: 
apps/repl: `pnpm start -p 4201`  
apps/tutorial: `pnpm start`

**Comment by NullVoxPopuli** [comment]
I've changed the top-level `pnpm start` to do this all for you. 
it'll boot:
 - tutorial
 - repl
 - ui addon
 - tailwind 
 
 If you run in to any issues lemme know!
