### ISSUE TITLE
Glimmer tutorial, text editing does not work after first load

### ISSUE THREAD

**Issue by nicolechung** [NullVoxPopuli/limber#860]
![typing-issue](https://user-images.githubusercontent.com/771170/233870475-1b8334b9-b6a7-438a-b69a-eef9207e3399.gif)

1. On first load, typing works.
2. When you advance to another page, typing does not appear.

Browser: Firefox 109.0.1

**Comment by NullVoxPopuli** [comment]
Thanks for reporting, is this any page, or just the two shown?

I tried to verify on mobile Firefox with the first two pages, and so far, i've yeah to replicate the issue. Maybe something more specific is involved?

**Comment by NullVoxPopuli** [comment]
I managed to reproduce the issue on a computer, using console.log. yay!

**Comment by nicolechung** [comment]
> Thanks for reporting, is this any page, or just the two shown?

I think it's any page...I noticed I was having problems going through the entire tutorial, took me a few tries to figure out what the issue is.

**Comment by NullVoxPopuli** [comment]
@nicolechung on my computer where I could replicate, I think the problem is resolved, can you verify?

**Comment by nicolechung** [comment]
Works for me now - thank you so much for fixing this!
